version: '3.8'
services:
  web:
    env_file:
      - ./config/.env
    depends_on:
      - db 
      - redis
    image: auth-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - .db:/data
    restart: always
    entrypoint: redis-server --appendonly yes

  db:
    image: mysql:8.0
    env_file:
      - ./config/.env
    container_name: mega
    restart: always
    environment:
      - MYSQL_DATABASE=DB_DATABASE
      - MYSQL_ROOT_PASSWORD=DB_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
